{{- if eq .Values.sumologic.eventCollectionEnabled true }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ printf "%s-events" (include "sumologic.fullname" .) }}
  labels:
    app: {{ printf "%s-events" (include "sumologic.labels.app" .) }}
    {{- include "sumologic.labels.common" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ printf "%s-events" (include "sumologic.labels.app" .) }}
  template:
    metadata:
      labels:
        app: {{ printf "%s-events" (include "sumologic.labels.app" .) }}
        {{- include "sumologic.labels.common" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "sumologic.fullname" . }}
{{- if .Values.eventsStatefulset.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.eventsStatefulset.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.eventsStatefulset.tolerations }}
      tolerations:
{{ toYaml .Values.eventsStatefulset.tolerations | indent 8 }}
{{- end }}
      volumes:
      - name: pos-files
        hostPath:
          path: /var/run/fluentd-pos
          type: ""
      - name: config-volume
        configMap:
          name: {{ printf "%s-events" (include "sumologic.fullname" .) }}
      securityContext:
        fsGroup: {{ .Values.sumologic.fluentd.securityContext.fsGroup }}
      containers:
      - name: fluentd-events
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.eventsStatefulset.resources | nindent 10 }}
        volumeMounts:
        - name: config-volume
          mountPath: /fluentd/etc/
        - name: pos-files
          mountPath: /mnt/pos/
{{- if .Values.sumologic.fluentd.persistence.enabled }}
        - name: buffer
          mountPath: "/fluentd/buffer"
{{- end}}
        livenessProbe:
          httpGet:
            path: /fluentd.pod.healthcheck?json=%7B%22log%22%3A+%22health+check%22%7D
            port: 9880
          initialDelaySeconds: 300
          periodSeconds: 30
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /fluentd.pod.healthcheck?json=%7B%22log%22%3A+%22health+check%22%7D
            port: 9880
          initialDelaySeconds: 30
          periodSeconds: 5
        env:
        - name: SUMO_ENDPOINT_EVENTS
          valueFrom:
            secretKeyRef:
              name: sumologic
              key: endpoint-events
        - name: VERIFY_SSL
          value: {{ .Values.sumologic.verifySsl| quote }}
        - name: FLUSH_INTERVAL
          value: {{ .Values.sumologic.flushInterval | quote }}
        - name: NUM_THREADS
          value: {{ .Values.sumologic.numThreads | quote }}
        - name: CHUNK_LIMIT_SIZE
          value: {{ .Values.sumologic.chunkLimitSize | quote }}
        - name: QUEUE_CHUNK_LIMIT_SIZE
          value: {{ .Values.sumologic.queueChunkLimitSize | quote }}
        - name: TOTAL_LIMIT_SIZE
          value: {{ .Values.sumologic.totalLimitSize | quote }}
{{- if .Values.sumologic.fluentd.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: buffer
    spec:
      accessModes: [{{ .Values.sumologic.fluentd.persistence.accessMode }}]
      storageClassName: {{ .Values.sumologic.fluentd.persistence.storageClass }}
      resources:
        requests:
          storage: {{ .Values.sumologic.fluentd.persistence.size }}
{{- end }}
{{- end }}
