{{- if .Values.fluentd.autoscaling.enabled}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ printf "%s-fluentd" (include "sumologic.fullname" .) }}
  labels:
    app: {{ template "sumologic.labels.app" . }}
    {{- include "sumologic.labels.common" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ printf "%s-fluentd" (include "sumologic.fullname" .) }}
  minReplicas: {{ .Values.fluentd.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.fluentd.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.fluentd.autoscaling.targetCPUUtilizationPercentage }}
{{- end -}}
