{{- if .Values.sumologic.cleanUpSecrets }}
apiVersion: batch/v1
kind: Job
metadata:
  name: collection-sumologic-secret-cleanup
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      serviceAccountName:  {{ template "sumologic.metadata.name.setup.roles.serviceaccount" . }}-cleanup
      containers:
        - name: kubectl
          image: bitnami/kubectl:1.17.4
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - kubectl delete secret sumologic; 
      restartPolicy: OnFailure
{{- end }}