{{- if .Values.sumologic.setupEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  {{ printf "%s-setup" (include "sumologic.fullname" .) }}
  annotations:
{{ toYaml .Values.sumologic.setup.serviceAccount.annotations | indent 4 }}
  labels:
    app: {{ template "sumologic.labels.app" . }}
    {{- include "sumologic.labels.common" . | nindent 4 }}
{{- end }}
